### ISSUE TITLE
Request to Update Package to the Latest Version on pub.dev

### ISSUE THREAD

**Issue by vinodh013** [duhanbalci/surrealdb_flutter#18]
Hi @duhanbalci,

I hope you're doing well. I noticed that there hasn't been an update to the package on pub.dev. The current version specified in pubspec.yaml is 7.0.0, while the version on pub.dev is still at 0.6.2.

I kindly request that you consider updating the package to the latest version on pub.dev.  

Thank you for your attention to this matter.

**Comment by duhanbalci** [comment]
Hi @vinodh013 

The package has been updated to version 7.0.0 on pub.dev.
