### ISSUE TITLE
Manage rpc timeout execption 

### ISSUE THREAD

**Issue by vinodh013** [duhanbalci/surrealdb_flutter#21]
After a certain time period of no request and response. How to re-establish connection to the database

**Comment by Crowdedlight** [comment]
Did you figure this out? 

I believe I am having a similar issue. My app works great when opened, but after being left on overnight and trying to use it the next morning I get "IAM permission error: not enough permission to do this" on a query that works normally. 

If I close and start the app, the same query works perfectly fine. 

I create the client:
```dart
var dclient = SurrealDB(dotenv.env['DATABASE_URL']!)..connect();
  await dclient.wait();
  await dclient.use('test', 'test');
  final token = await dclient.signin(user: username, pass: password, namespace: "test", database: "test");
  ```
  
  When it fails I try to "re-connect" with:
  ```dart
        // try to reconnect
      dclient.close();
      dclient.connect();
      await dclient.wait();
      await dclient.use('test', 'test');
      await dclient.authenticate(token);
  ``` 
  
  But that does not seem to work. It continues to fail with a permission error until I stop the app and start it again.

**Comment by Crowdedlight** [comment]
@vinodh013 Did you solve this? I still deal with the same challenge, and tried different ways of trying to reauth if it fails, but not found something that works yet. Still have the connection crash unable to reauth after longer times of no requests.

**Comment by vinodh013** [comment]
Hi @Crowdedlight,

To maintain the connection with the server, especially when using RPC, we need to periodically send a ping to keep the connection alive. For REST, this isn’t necessary since it works over stateless HTTP requests. But for RPC, timers are needed to keep the connection active.

Here are the functions you can use:
```
void startPingTimer() {
    // Cancel any existing timer first
    _pingTimer?.cancel();

    // Start a new periodic timer
    _pingTimer = Timer.periodic(config.pingInterval, (timer) {
      client
          .ping()
          .then((value) {
            print('SurrealDB ping success');
          })
          .catchError((error) {
            print('SurrealDB ping failed: $error');
            // Auto-reconnect logic could be added here
          });
    });
  }

  /// Stop the ping timer
  void stopPingTimer() {
    if (_pingTimer != null) {
      _pingTimer!.cancel();
      _pingTimer = null;
      print('SurrealDB ping timer stopped');
    }
  }
```

**Comment by Crowdedlight** [comment]
Thanks alot! Will give it a go :)
