### ISSUE TITLE
Warnings Automatic inference of the protocol format is deprecated in SurrealDB 2.0 and will be removed in SurrealDB 3.0.

### ISSUE THREAD

**Issue by willyfromtheblock** [duhanbalci/surrealdb_flutter#26]
> surrealdb 2.0.0 

```
2024-11-01T23:09:37.278310Z  WARN surreal::net::rpc: Automatic inference of the protocol format is deprecated in SurrealDB 2.0 and will be removed in SurrealDB 3.0.
2024-11-01T23:09:37.278315Z  WARN surreal::net::rpc: Please upgrade any client to ensure that the connection format is specified.

```
reference:
https://github.com/surrealdb/surrealdb/issues/4884

I will keep a look, what exactly they are fixing in the go/python sdk

**Comment by duhanbalci** [comment]
SurrealDB requires you to specify a WebSocket subprotocol. [link to code](https://github.com/surrealdb/surrealdb/blob/898f0733cce5fef6d8315a1dc715fae84e705845/src/net/rpc.rs#L66)
However, it only checks if the protocol header exists. I will add an empty string as the subprotocol to bypass the warning.

**Comment by duhanbalci** [comment]
SurrealDB requires you to specify a WebSocket subprotocol. [link to code](https://github.com/surrealdb/surrealdb/blob/898f0733cce5fef6d8315a1dc715fae84e705845/src/net/rpc.rs#L66)
However, it only checks if the protocol header exists. I will add an empty string as the subprotocol to bypass the warning.

**Comment by duhanbalci** [comment]
SurrealDB requires you to specify a WebSocket subprotocol. [link to code](https://github.com/surrealdb/surrealdb/blob/898f0733cce5fef6d8315a1dc715fae84e705845/src/net/rpc.rs#L66)
However, it only checks if the protocol header exists. I will add an empty string as the subprotocol to bypass the warning.

**Comment by vinodh013** [comment]
Hi @duhanbalci  I am getting this error 

`RethrownDartError: WebSocketChannelException: SyntaxError: Failed to construct 'WebSocket': The subprotocol '' is invalid.
`

This issue has been addressed above,  Is there any solution to resolve this problem.
